# -*- coding: utf-8 -*-
"""bubble sort.c

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvHLW-lZViaetJKsONPAb331S5UL_WRU
"""

#include<stdio.h>
void bubble_sort(int a[],int n)
{
int i,j;
for(i=0;i<n-1;i++){
    for(j=0;j<n-i-1;j++){
        if(a[j]>a[j+1]){
            int temp=a[j];
            a[j]=a[j+1];
            a[j+1]=temp;
        }
    }
}
}
int main(){
    int a[]={64,3,7,23,90};
    int n=sizeof(a)/sizeof(a[0]);
    bubble_sort(a,n);
    printf("sorted array");
    for(int i=0;i<n;i++){
        printf("%d ",a[i]);
    }
    return 0;
}